### ISSUE TITLE
Service doesn't start after reboot. 

### ISSUE THREAD

**Issue by Aimen06** [X3n0m0rph59/eruption-roccat-vulcan#1]
Hi,
I have managed to compile the project without error.
But nothing happen after reboot.
When i type systemctl start eruption.service i get Failed to start eruption.service: Unit eruption.service not found.
I use debian unstable.
Do you know what is the problem ?
Thx

**Comment by X3n0m0rph59** [comment]
Thanks for your bug report!

Seems like systemd did not find the unit file of the eruption service.
The file `support/systemd/eruption.service` has to be copied from the project's directory to the systemd unit directory `/lib/systemd/system/`.

I'm going to prepare packages for Debian very soon! Then it will be much easier for you to deploy.

**Comment by Aimen06** [comment]
Thanks for the reply i will try :)
