### ISSUE TITLE
Feature Request: Make the brightness dial work

### ISSUE THREAD

**Issue by 1drp** [X3n0m0rph59/eruption-roccat-vulcan#24]
The Brightness Dial (Volume knob with the "FX" button selected) registers as a whole keyboard event, but brightness is not changed.  It would be nice to be able to change brightness with this dial again (especially useful if it also changes mouse brightness).

**Comment by X3n0m0rph59** [comment]
Hi, thanks for your suggestion! I have pushed the required changes to the master branch. Please see commit 9c6a2ef.

This feature will be included in the next release.
