### ISSUE TITLE
Volume controls not working after Update

### ISSUE THREAD

**Issue by ACR-Jeff** [X3n0m0rph59/eruption-roccat-vulcan#9]
Keyboard: Roccat Vulcan 120 AIMO
Distro: Linux Mint 20
Updated to eruption-roccat-vulcan version 0.1.11-ubuntu7
Issue: Volume controls not working after Update
Read and followed all instructions in the entire README
Followed "Support for Audio Playback and Capture" instructions
Without any resolution.
Any help would be appreciated.
Thanks

**Comment by X3n0m0rph59** [comment]
Hi, thanks for your bug report!

I can confirm that this is a bug with the Ubuntu PPA packages. I am currently building new and fixed Ubuntu packages on Launchpad.

**Comment by X3n0m0rph59** [comment]
OK, updated packages are available now!

Please feel free to re-open this bug report if you have further issues.
